import OpenAI from "openai";
import { describe,expect,it,vi } from "vitest";
import { getSafeOpenAIErrorMessage } from "../app/lib/aiErrors.server";
import { buildBatchReconciliationPrompt, type BranchEvidence } from "../app/lib/development/copilot";
import { buildDevelopmentCopilotContext, DEVELOPMENT_CONTEXT_BUDGETS, withContextOverflowFallback } from "../app/lib/development/context-budget";

const huge=(label:string,size=80_000)=>`${label}:${"x".repeat(size)}`;
function record(){return {request:{id:"request-1",title:"Locations show Unknown",problem:"Locations save but later show Unknown Location.",why_decision:"Preserve the human-selected location IDs and never overwrite QA decisions.",priority:"P1",overall_status:"working",notes:"Tenant isolation is a hard blocker."},links:[{provider:"github",type:"issue",external_id:"620",url:"https://github.test/issues/620"},{provider:"github",type:"pull_request",external_id:"630",url:"https://github.test/pull/630"}],branches:[{branch:"adam",state:"present",commit_sha:"abc123",checked_at:"2026-08-24"},{branch:"main",state:"not_present",commit_sha:"def456",checked_at:"2026-08-24"}],qa:[{stage:"ADAM_QA",status:"passed"},{stage:"JOE_QA",status:"failed",notes:"Unknown Location remains"}],approvals:[],githubItems:[{kind:"issue",number:620,title:"Location persistence",state:"open",github_updated_at:"now",payload_json:JSON.stringify({body:"Issue body",labels:["bug"]})},{kind:"pull_request",number:630,title:"Preserve location IDs",state:"open",github_updated_at:"now",payload_json:JSON.stringify({body:"PR body",sourceBranch:"fix/locations",targetBranch:"main",headSha:"abc123",checks:[{status:"completed",conclusion:"success"}],changedFiles:Array.from({length:120},(_,index)=>({filename:`file-${index}.ts`,patch:huge("patch",10_000)}))})}]};}
function copilot(){const prompts=Array.from({length:12},(_,index)=>({id:`p${index}`,version:12-index,is_current:index===0,generated_text:huge(`prompt-${index}`,30_000),edited_text:null,prompt_type:"implementation",target_tool:"Codex"}));const thread=[{id:"human-old",entry_type:"HUMAN",content:"Decision: preserve Joe QA and do not replace the environment workflow.",created_at:"1",metadata_json:null},...Array.from({length:20},(_,index)=>({id:`system-${index}`,entry_type:"SYSTEM",content:huge("duplicate sync event",10_000),created_at:`2-${index}`,metadata_json:JSON.stringify({kind:"sync"})})),...Array.from({length:8},(_,index)=>({id:`response-${index}`,entry_type:"CODEX",content:huge(`large response ${index}`,45_000),created_at:`3-${index}`,metadata_json:JSON.stringify({kind:"model_response"})})),{id:"failure",entry_type:"HUMAN",content:"Latest failure: Worker build reports locationIds stripped by validation.",created_at:"4",metadata_json:JSON.stringify({kind:"failure_report"})}];return {state:{work_state:"NEEDS_FOLLOWUP",suggested_next_step:"Fix validation and rerun focused tests",visual_observations_json:JSON.stringify({observations:[huge("old screenshot",20_000)]})},prompts,thread,attachments:Array.from({length:20},(_,index)=>({id:`a${index}`,caption:`Screenshot ${index}`,category:index===19?"Error":"Reference",uploaded_at:String(index)})),analyses:Array.from({length:8},(_,index)=>({result:index?"Partial":"Failure",plain_english_result:huge(`analysis ${index}`,8_000),important_facts_json:JSON.stringify([{fact:"Reported only"}]),recommended_next_step:"Review"}))};}

describe("Development Copilot context budget",()=>{
  it("leaves a small request intact",()=>{const built=buildDevelopmentCopilotContext({operation:"Development Copilot summary",record:record(),copilot:{state:{work_state:"NEEDS_PROMPT"},prompts:[],thread:[],attachments:[],analyses:[]},currentInstruction:"Summarize"});expect((built.context as any).humanRequest.problem).toContain("Unknown Location");expect((built.context as any).humanRequest.whyDecision).toContain("never overwrite QA");});
  it("bounds a realistic large PR-backed request with headroom",()=>{const built=buildDevelopmentCopilotContext({operation:"Development Copilot summary",record:record(),copilot:copilot(),currentInstruction:"Generate summary"});expect(built.diagnostics.estimatedInputTokens).toBeLessThanOrEqual(DEVELOPMENT_CONTEXT_BUDGETS["gpt-5-mini"].safeInputTokens);expect(built.serialized).not.toContain("patch:");expect(built.serialized.length).toBeLessThanOrEqual(105_000);});
  it("retains authoritative state, current failure, human decisions and one current prompt",()=>{const built=buildDevelopmentCopilotContext({operation:"Development Copilot prompt",record:record(),copilot:copilot(),currentInstruction:"Continue"});expect(built.serialized).toContain("abc123");expect(built.serialized).toContain("locationIds stripped");expect(built.serialized).toContain("preserve Joe QA");expect(built.diagnostics.promptsConsidered).toBe(12);expect(built.diagnostics.promptsIncluded).toBe(1);expect(built.serialized).not.toContain("prompt-1:");});
  it("compacts old responses and repetitive SYSTEM events",()=>{const built=buildDevelopmentCopilotContext({operation:"Development Copilot follow-up prompt",record:record(),copilot:copilot(),currentInstruction:"Continue"});expect(built.diagnostics.threadEntriesSummarized).toBeGreaterThan(built.diagnostics.threadEntriesIncludedVerbatim);expect(built.serialized).not.toContain("duplicate sync event");expect(built.serialized).toContain("Original history remains in DEVOS");});
  it("uses one canonical GitHub representation and bounded screenshot context",()=>{const built=buildDevelopmentCopilotContext({operation:"Development Copilot summary",record:record(),copilot:copilot(),currentInstruction:"Summarize"});expect((built.serialized.match(/Preserve location IDs/g)||[])).toHaveLength(1);expect(built.diagnostics.attachmentsIncluded).toBeLessThanOrEqual(12);expect(built.imageLimit).toBe(2);});
  it("retries context overflow exactly once in aggressive mode",async()=>{const calls:string[]=[];const result=await withContextOverflowFallback(async mode=>{calls.push(mode);if(mode==="normal")throw Object.assign(new Error("too large"),{code:"context_length_exceeded"});return "ok";});expect(result.value).toBe("ok");expect(calls).toEqual(["normal","aggressive"]);});
  it("never loops and returns a DEVOS-specific final overflow error",async()=>{const invoke=vi.fn(async()=>{throw Object.assign(new Error("context_length_exceeded"),{code:"context_length_exceeded"});});await expect(withContextOverflowFallback(invoke)).rejects.toThrow("Development Copilot context is too large to process safely");expect(invoke).toHaveBeenCalledTimes(2);});
  it("does not retry non-overflow provider errors",async()=>{const invoke=vi.fn(async()=>{throw new Error("network")});await expect(withContextOverflowFallback(invoke)).rejects.toThrow("network");expect(invoke).toHaveBeenCalledOnce();});
  it("uses caller-specific error attribution while preserving Content/LinkedIn wording",()=>{const error=Object.assign(Object.create(OpenAI.BadRequestError.prototype),{message:"bad input",status:400,code:"context_length_exceeded",type:"invalid_request_error",param:"input"});expect(getSafeOpenAIErrorMessage(error,{label:"Development Copilot summary"})).toContain("Development Copilot summary request");expect(getSafeOpenAIErrorMessage(error,{label:"Development Copilot prompt"})).toContain("Development Copilot prompt request");expect(getSafeOpenAIErrorMessage(error,{label:"Development Copilot failure analysis"})).toContain("Development Copilot failure analysis request");expect(getSafeOpenAIErrorMessage(error,{label:"Branch Sync remediation prompt"})).toContain("Branch Sync remediation prompt request");expect(getSafeOpenAIErrorMessage(error,"plan")).toContain("weekly content plan request");expect(getSafeOpenAIErrorMessage(error,"post")).toContain("post draft request");expect(getSafeOpenAIErrorMessage(error,"image")).toContain("image request");});
  it("bounds batch Branch Sync prompt generation",()=>{const branch=(id:number):BranchEvidence=>({requestId:`r${id}`,title:huge(`Request ${id}`,500),adam:{sha:"a",state:"present",checkedAt:"now"},joe:{sha:null,state:"unknown",checkedAt:null},dev:{sha:null,state:"unknown",checkedAt:null},main:{sha:null,state:"unknown",checkedAt:null},confidence:"UNKNOWN",ci:"Unknown",adamQa:"pending",joeQa:"pending",generatedAt:"now"});const prompt=buildBatchReconciliationPrompt(Array.from({length:100},(_,index)=>branch(index)));expect(prompt.length).toBeLessThanOrEqual(100_000);expect(prompt).toContain("remaining 75");});
});
