ALTER TABLE playbooks ADD COLUMN relationship_type TEXT;
ALTER TABLE playbooks ADD COLUMN monthly_long_form_asset TEXT;
ALTER TABLE playbooks ADD COLUMN content_sources TEXT;
ALTER TABLE playbooks ADD COLUMN primary_post_formats TEXT;
ALTER TABLE playbooks ADD COLUMN example_topics TEXT;
ALTER TABLE playbooks ADD COLUMN cross_team_collaboration TEXT;
ALTER TABLE playbooks ADD COLUMN ninety_day_audience_goal TEXT;
ALTER TABLE playbooks ADD COLUMN ninety_day_content_goal TEXT;
ALTER TABLE playbooks ADD COLUMN primary_kpi TEXT;
ALTER TABLE playbooks ADD COLUMN secondary_kpi TEXT;

INSERT INTO playbooks (
  role_name, relationship_type, primary_audience, secondary_audience,
  primary_expertise, core_buyer_problem, positioning_statement, recurring_series,
  weekly_original_posts, weekly_short_posts, weekly_meaningful_comments,
  weekly_new_connections, monthly_long_form_asset, content_sources,
  primary_post_formats, example_topics, lead_magnet, soft_cta,
  qualified_buying_signal, lead_handoff_action, cross_team_collaboration,
  ninety_day_audience_goal, ninety_day_content_goal, primary_kpi, secondary_kpi,
  guardrail, updated_at
) VALUES
('Founder / Managing Partner', 'Executive', 'CEOs, CIOs, CFOs, IT executives', 'MSP owners and strategic partners', 'Telecom procurement strategy, industry direction and customer advocacy', 'Enterprise telecom buying is fragmented, opaque and difficult to manage', 'Helping enterprises make better carrier, connectivity and telecom-contract decisions', 'What Telecom Buyers Are Not Being Told', 2, 1, 20, 25, 'Executive telecom procurement briefing', 'Customer conversations, market observations, carrier developments and company strategy', 'Text posts, short videos and opinion pieces', 'Why enterprises should not allow incumbent carriers to control renewal timing; why telecom procurement needs an owner', 'Executive Telecom Procurement Scorecard', 'Happy to share the scorecard we use.', 'CIO mentions renewal, cost pressure, service instability, acquisition or multi-location complexity', 'Route to senior sales owner and note executive context', 'Amplify insights from every specialist without reposting identical copy', '1,000 relevant connections or followers', '30 strong original posts', 'Executive conversations generated', 'Profile views from target titles', 'Avoid unsupported market claims and avoid turning every post into a company pitch', CURRENT_TIMESTAMP),
('Enterprise Connectivity Advisor', 'Advisor', 'CIOs, VPs of Infrastructure, IT directors', 'Network architects and procurement leaders', 'DIA, broadband, Ethernet, MPLS replacement and enterprise access strategy', 'Enterprises struggle to balance cost, resilience, carrier diversity and contract terms', 'Helping enterprise IT teams design and source reliable connectivity without carrier bias', 'The Enterprise Circuit Decision', 2, 1, 15, 20, 'Enterprise Connectivity Buyer’s Guide', 'Former projects, architecture decisions, carrier comparisons and buying mistakes', 'Technical explainers, checklists and case narratives', 'DIA versus broadband; primary and backup design; evaluating diverse entrances', 'Enterprise Circuit Requirements Template', 'I can send the requirements template.', 'Buyer is redesigning WAN, replacing MPLS, renewing circuits or reporting recurring outages', 'Route to enterprise opportunity owner with locations and timeline', 'Network Engineer, SD-WAN Advisor, Carrier Analyst', '700 relevant connections', '24 posts and one guide', 'Qualified enterprise conversations', 'Saves and document downloads', 'Do not present generalized carrier claims as universal facts', CURRENT_TIMESTAMP),
('Retail Connectivity Advisor', 'Advisor', 'Retail CIOs, IT directors, network leaders, store systems leaders', 'Store development, construction, procurement and operations executives', 'Multi-location retail connectivity, store openings, broadband, DIA, LTE/5G backup, vendor coordination and lifecycle management', 'Store openings are delayed by ordering intervals, landlord access, construction surprises, inconsistent carrier coverage and fragmented circuit inventory', 'Helping multi-location retailers open stores on time and keep every location connected', 'Retail Network Opening Playbook', 2, 2, 20, 25, 'Retail Store Connectivity Readiness Checklist', 'Store-opening experience, construction coordination, outage situations, carrier interval lessons and retail technology trends', 'Checklists, timelines, diagrams, short videos and anonymized project stories', 'What must happen 120 days before a store opens; broadband versus fiber by location type; LTE backup standards; landlord and MPOE access; seasonal retail freeze periods', 'Retail Store Opening Connectivity Checklist', 'Comment ''opening'' and I’ll send the checklist.', 'Retailer announces expansion, acquisition, remodel program, POS refresh, SD-WAN rollout or repeated store outages', 'Route to retail sales owner; capture store count, opening dates, incumbent providers and decision team', 'Project Manager, Wireless Advisor, Network Engineer and Procurement Advisor', '800 highly relevant retail connections', '30 posts, 12 retail comments weekly and one checklist', 'Meetings with retail IT or store-development leaders', 'Checklist requests and target-account engagement', 'Do not claim named retailer experience without authorization; no confidential site details', CURRENT_TIMESTAMP),
('Healthcare Connectivity Advisor', 'Advisor', 'Healthcare CIOs, infrastructure directors and hospital IT leaders', 'Clinic operations, security teams and healthcare MSPs', 'Clinical network availability, multi-site healthcare access, redundancy and compliance-aware sourcing', 'Healthcare networks require uptime while managing old contracts, remote clinics and limited local carrier options', 'Helping healthcare organizations improve connectivity resilience across hospitals, clinics and remote sites', 'Connected Care Infrastructure', 2, 1, 15, 20, 'Healthcare Connectivity Risk Assessment', 'Healthcare projects, outage risks, rural access challenges and compliance considerations', 'Text posts, risk lists and architecture explainers', 'Clinic failover; circuit diversity; rural broadband realities; acquisition integration', 'Healthcare Connectivity Risk Checklist', 'I can share the site-risk worksheet.', 'Healthcare group opens clinics, acquires practices, reports outages or launches telehealth expansion', 'Route with facility count, clinical priority and timing', 'Security Advisor, Wireless Advisor and Project Manager', '500 healthcare connections', '24 posts and one assessment', 'Healthcare discovery calls', 'Engagement from healthcare IT titles', 'Avoid making legal or compliance guarantees', CURRENT_TIMESTAMP),
('Manufacturing Connectivity Advisor', 'Advisor', 'Plant IT directors, infrastructure leaders and operations executives', 'OT leaders, plant managers and industrial MSPs', 'Plant connectivity, uptime, diverse carrier access and operational continuity', 'A single circuit failure can affect production, shipping, systems access and operational visibility', 'Helping manufacturers design connectivity that supports production instead of becoming a production risk', 'The Connected Plant', 2, 1, 15, 20, 'Plant Connectivity Resilience Checklist', 'Plant projects, industrial outages, rural carrier limitations and operational requirements', 'Diagrams, failure scenarios and project stories', 'Fiber path diversity; backup connectivity; new facility timelines; carrier demarcation issues', 'Plant Network Resilience Checklist', 'Happy to compare your current failover design against the checklist.', 'Factory expansion, plant acquisition, downtime, automation program or new warehouse', 'Route with plant locations, downtime impact and current topology', 'Network Engineer, Wireless Advisor and Construction Advisor', '500 manufacturing connections', '24 posts and one checklist', 'Plant network opportunities', 'Comments from operations and IT leaders', 'Do not overstate engineering qualifications or safety expertise', CURRENT_TIMESTAMP),
('Hospitality Connectivity Advisor', 'Advisor', 'Hotel IT executives, ownership groups and management companies', 'Property operations, guest technology leaders and hospitality MSPs', 'Hotel Internet, property openings, guest Wi-Fi backhaul, voice and multi-property sourcing', 'Properties need reliable guest and operational connectivity despite ownership changes, construction schedules and inconsistent local providers', 'Helping hotel groups standardize connectivity across every property without slowing openings or renovations', 'The Connected Property', 2, 1, 15, 20, 'Hotel Opening Connectivity Timeline', 'Hotel openings, renovations, guest-experience issues and property-management technology', 'Text stories, timelines and checklists', 'Opening timelines; backup Internet; voice transitions; franchise standards; event-bandwidth planning', 'Hotel Connectivity Opening Checklist', 'I can send the property-opening timeline.', 'New hotel, acquisition, renovation, brand conversion or guest Wi-Fi complaints', 'Route with property count, brand, opening dates and ownership structure', 'Retail Advisor, Project Manager and Voice Advisor', '400 hospitality connections', '24 posts and one timeline', 'Hospitality meetings', 'Resource downloads', 'Do not imply brand authorization or endorsements', CURRENT_TIMESTAMP),
('Financial Services Connectivity Advisor', 'Advisor', 'Bank and financial-services CIOs, infrastructure and branch technology leaders', 'Compliance, security and branch operations teams', 'Branch connectivity, resilience, carrier diversity and acquisition integration', 'Banks and financial institutions need resilient branch and office networks with disciplined vendor management', 'Helping financial institutions modernize branch connectivity while reducing carrier complexity', 'Branch Network Briefing', 2, 1, 15, 20, 'Branch Connectivity Due-Diligence Guide', 'Branch projects, mergers, outage risk and vendor-management experience', 'Text posts, due-diligence lists and executive summaries', 'Branch backup; acquisition conversion; contract alignment; carrier diversity', 'Branch Network Due-Diligence Checklist', 'I can share the branch review checklist.', 'Bank merger, branch expansion, technology refresh or service incident', 'Route to financial vertical owner and capture compliance stakeholders', 'Contract Advisor, Security Advisor and Project Manager', '400 financial-services connections', '24 posts and one guide', 'Financial-services opportunities', 'Target-title engagement', 'Avoid compliance assurances or confidential institutional details', CURRENT_TIMESTAMP),
('Government and Federal Telecom Advisor', 'Advisor', 'Federal IT, contracting officers, program managers and integrators', 'State and local government technology leaders', 'Federal telecom acquisition, contracting structures, carrier services and program execution', 'Agencies and integrators must navigate procurement, compliance, complex locations and long delivery timelines', 'Helping government buyers and integrators navigate telecom sourcing and delivery with fewer surprises', 'Federal Connectivity Field Notes', 2, 1, 15, 15, 'Federal Telecom Acquisition Checklist', 'Public solicitations, acquisition experience, delivery lessons and official government sources', 'Text posts, clause explainers and acquisition checklists', 'Ordering timelines; service-location validation; subcontractor coordination; transition risks', 'Federal Telecom Acquisition Checklist', 'I can share the acquisition-planning worksheet.', 'New solicitation, recompete, base expansion, task order or integrator seeking a telecom partner', 'Route to federal opportunity owner with solicitation data and due dates', 'Compliance Advisor, Project Manager and Carrier Analyst', '400 federal and integrator connections', '24 posts and one checklist', 'Federal partner conversations', 'Solicitation-related inquiries', 'Use only public information; never imply agency endorsement or provide legal conclusions', CURRENT_TIMESTAMP),
('MSP and Channel Advisor', 'Advisor', 'MSP owners, technology advisors, VARs and IT consultants', 'MSP sales and operations leaders', 'Channel partnerships, telecom commissions, customer ownership and recurring-revenue strategy', 'MSPs often leave telecom revenue and customer control to outside sellers', 'Helping MSPs add carrier services without creating operational chaos or damaging client trust', 'The MSP Telecom Revenue Playbook', 2, 2, 20, 25, 'MSP Telecom Partnership Guide', 'Channel experience, partner questions, compensation structures and service-delivery lessons', 'Text posts, revenue models and partner stories', 'When MSPs should partner versus build; protecting customer relationships; referral workflow', 'MSP Telecom Partnership Guide', 'DM me ''partner'' and I’ll send the guide.', 'MSP asks about referral revenue, commissions, customer ownership or service support', 'Route to channel leader with partner size, client base and geography', 'Founder, Commission Advisor and Customer Success Advisor', '900 MSP and advisor connections', '30 posts and one partner guide', 'Qualified channel partners', 'Guide requests and partner referrals', 'Never misstate commission terms or guarantee revenue', CURRENT_TIMESTAMP),
('Commercial Real Estate and Construction Advisor', 'Advisor', 'Commercial brokers, developers, general contractors and tenant coordinators', 'Corporate real-estate and facilities leaders', 'Telecom due diligence, building access, site readiness and construction coordination', 'Connectivity is often addressed too late in leases, relocations and construction schedules', 'Helping real-estate and construction teams identify telecom risk before it delays occupancy', 'Before the Lease Is Signed', 2, 1, 20, 25, 'Site Connectivity Due-Diligence Checklist', 'Building surveys, construction coordination, demarcation issues and occupancy timelines', 'Photo explainers, checklists and cautionary stories', 'MPOE access; landlord approvals; fiber construction; site surveys; move deadlines', 'Site Connectivity Due-Diligence Checklist', 'I can send the checklist before your next site review.', 'New lease, headquarters move, warehouse construction, tenant improvement or opening delay', 'Route with address, occupancy date and construction contacts', 'Retail Advisor, Project Manager and Field Services Advisor', '700 commercial-real-estate connections', '24 posts and one checklist', 'Introductions to tenants and developers', 'Address-specific assessments', 'Do not publish customer addresses or private building access details', CURRENT_TIMESTAMP)
ON CONFLICT(role_name) DO UPDATE SET
  relationship_type=excluded.relationship_type,
  primary_audience=excluded.primary_audience,
  secondary_audience=excluded.secondary_audience,
  primary_expertise=excluded.primary_expertise,
  core_buyer_problem=excluded.core_buyer_problem,
  positioning_statement=excluded.positioning_statement,
  recurring_series=excluded.recurring_series,
  weekly_original_posts=excluded.weekly_original_posts,
  weekly_short_posts=excluded.weekly_short_posts,
  weekly_meaningful_comments=excluded.weekly_meaningful_comments,
  weekly_new_connections=excluded.weekly_new_connections,
  monthly_long_form_asset=excluded.monthly_long_form_asset,
  content_sources=excluded.content_sources,
  primary_post_formats=excluded.primary_post_formats,
  example_topics=excluded.example_topics,
  lead_magnet=excluded.lead_magnet,
  soft_cta=excluded.soft_cta,
  qualified_buying_signal=excluded.qualified_buying_signal,
  lead_handoff_action=excluded.lead_handoff_action,
  cross_team_collaboration=excluded.cross_team_collaboration,
  ninety_day_audience_goal=excluded.ninety_day_audience_goal,
  ninety_day_content_goal=excluded.ninety_day_content_goal,
  primary_kpi=excluded.primary_kpi,
  secondary_kpi=excluded.secondary_kpi,
  guardrail=excluded.guardrail,
  updated_at=CURRENT_TIMESTAMP;

INSERT INTO playbooks (
 role_name,relationship_type,primary_audience,secondary_audience,primary_expertise,core_buyer_problem,positioning_statement,recurring_series,
 weekly_original_posts,weekly_short_posts,weekly_meaningful_comments,weekly_new_connections,monthly_long_form_asset,content_sources,primary_post_formats,
 example_topics,lead_magnet,soft_cta,qualified_buying_signal,lead_handoff_action,cross_team_collaboration,ninety_day_audience_goal,ninety_day_content_goal,
 primary_kpi,secondary_kpi,guardrail,updated_at
) VALUES
('Carrier Pricing and Market Analyst','Contractor','CIOs, procurement teams and technology advisors','Carrier sellers and industry analysts','Carrier pricing patterns, market structures and offer comparison','Buyers lack context for whether quotes and terms are competitive','Helping buyers understand the variables behind telecom pricing without pretending every location is the same','What Drives This Quote?',2,2,20,20,'Quarterly Connectivity Pricing Brief','Approved quote data, public promotions, carrier announcements and anonymized historical experience','Charts, quote breakdowns and analytical posts','Why two nearby addresses receive different prices; NRC versus MRC tradeoffs; term effects','Carrier Quote Comparison Worksheet','I can share the comparison framework.','Buyer shares renewal price, quote discrepancy or multi-carrier evaluation','Route to procurement owner; request address list and requirements through approved channel','Procurement Advisor, Founder and Data Analyst','700 procurement and IT connections','30 posts and one quarterly brief','Pricing-assessment opportunities','Saves, shares and worksheet requests','Use approved, anonymized and current data; never publish confidential carrier rates',CURRENT_TIMESTAMP),
('Carrier Relationship Advisor','Advisor','Enterprise buyers and technology advisors','Carrier account teams and escalation contacts','Carrier capabilities, fit, escalation practices and relationship management','Buyers often select carriers based on logo familiarity rather than location-specific fit and execution','Helping enterprises choose and manage carriers based on actual requirements and local capability','Choosing the Right Carrier for the Job',2,1,15,20,'Carrier Evaluation Scorecard','Carrier experience, public network information and delivery lessons','Text posts, scorecards and balanced comparisons','National versus regional carrier; evaluating support; escalation planning','Carrier Evaluation Scorecard','I can send the scorecard we use.','Buyer is comparing carriers or struggling with incumbent support','Route to enterprise or procurement sales owner','Carrier Analyst, Customer Success Advisor and Project Manager','500 buyer and carrier connections','24 posts and one scorecard','Carrier-comparison consultations','Comments from carrier and buyer audiences','Maintain balanced, factual commentary and disclose material relationships where appropriate',CURRENT_TIMESTAMP),
('Network Engineering Advisor','Advisor','Network architects, infrastructure leaders and IT directors','MSP engineers and solutions architects','WAN architecture, redundancy, bandwidth, routing and access design','Commercial decisions are often made without understanding technical dependencies','Helping IT teams translate business requirements into resilient access and WAN designs','Network Design in Plain English',2,2,20,20,'WAN Requirements Worksheet','Architecture experience, public standards, anonymized designs and troubleshooting lessons','Diagrams, whiteboard videos and technical explainers','Active-active versus failover; BGP basics; circuit diversity; bandwidth planning','WAN Requirements Worksheet','I can share the design-input worksheet.','Network redesign, SD-WAN evaluation, data-center move or resilience concern','Route to solutions engineering with topology and requirements','SD-WAN Advisor, Wireless Advisor and Enterprise Advisor','700 technical connections','30 posts and four diagrams','Technical discovery meetings','Technical saves and shares','Do not provide unsafe implementation instructions or claim to have reviewed a design without adequate facts',CURRENT_TIMESTAMP),
('SD-WAN and SASE Advisor','Advisor','CIOs, network and security leaders','MSPs and transformation consultants','SD-WAN, SASE, underlay design, migration planning and vendor evaluation','Organizations buy overlay platforms without addressing underlay quality, operational ownership or migration sequencing','Helping enterprises align SD-WAN and SASE strategy with the real-world connectivity underneath it','The Underlay Matters',2,1,15,20,'SD-WAN Readiness Assessment','Deployment experience, vendor documentation and architecture lessons','Text posts, migration diagrams and readiness checklists','Underlay diversity; broadband use; managed versus co-managed; migration sequencing','SD-WAN Readiness Checklist','I can send the readiness assessment.','SD-WAN RFP, MPLS replacement, security convergence or multi-site refresh','Route to enterprise architect and sales owner','Network Engineer, Security Advisor and Project Manager','600 network-leader connections','24 posts and one assessment','SD-WAN sourcing opportunities','Assessment requests','Avoid vendor bias and unsupported performance comparisons',CURRENT_TIMESTAMP),
('Wireless and Backup Connectivity Advisor','Advisor','IT directors, retail and field operations leaders','Construction, fleet and remote-site teams','LTE, 5G, fixed wireless, satellite and backup connectivity','Wired circuits may be delayed, unavailable or insufficient as the only access method','Helping organizations use wireless intelligently for backup, temporary and hard-to-reach locations','When Fiber Is Not Ready',2,1,15,20,'Wireless Backup Planning Guide','Wireless deployments, coverage challenges, public coverage data and outage cases','Demos, diagrams and deployment stories','LTE failover; 5G primary access; construction trailers; pop-up sites; satellite backup','Wireless Backup Planning Guide','I can share the wireless use-case matrix.','New location before fiber delivery, rural site, event, temporary facility or resilience requirement','Route with address, application, data use and installation date','Retail Advisor, Manufacturing Advisor and Network Engineer','500 operations and IT connections','24 posts and one guide','Wireless opportunities','Guide requests','Do not guarantee coverage without a site-specific assessment',CURRENT_TIMESTAMP),
('UCaaS and Voice Advisor','Advisor','CIOs, voice managers and IT directors','Contact-center, operations and customer-service leaders','UCaaS, SIP, analog replacement, POTS migration and voice transformation','Organizations underestimate number inventory, analog dependencies, emergency calling and change management','Helping enterprises modernize voice without losing numbers, critical lines or operational control','Voice Migration Mistakes',2,1,15,20,'Voice Migration Inventory Template','Voice migrations, number-porting lessons and operational dependencies','Text posts, inventories and migration stories','POTS replacement; elevator and alarm lines; number porting; UCaaS adoption','Voice Migration Inventory Template','I can send the inventory template.','Phone-system replacement, analog-line audit, office move or contact-center change','Route to voice specialist with seat count, locations and current platform','Project Manager, Compliance Advisor and Enterprise Advisor','500 IT and voice connections','24 posts and one template','Voice discovery calls','Template downloads','Avoid emergency-calling or regulatory guarantees',CURRENT_TIMESTAMP),
('Data Center and Cloud Connectivity Advisor','Advisor','Infrastructure leaders, cloud architects and data-center managers','MSPs and enterprise architects','Colocation, cloud on-ramps, cross-connects, transport and data-center migrations','Data-center and cloud projects depend on access circuits, cross-connect details and coordinated timelines','Helping enterprises connect offices, clouds and data centers without missing the physical dependencies','Cloud Still Needs a Network',2,1,15,20,'Data Center Connectivity Planning Guide','Data-center deployments, cloud connectivity designs and migration lessons','Architecture diagrams and planning checklists','Cloud on-ramps; cross-connect lead times; colo selection; transport diversity','Data Center Connectivity Planning Guide','I can share the dependency checklist.','Colocation move, cloud migration, disaster-recovery project or data-center exit','Route to infrastructure owner with sites, providers and target dates','Network Engineer, Project Manager and Carrier Analyst','500 cloud and infrastructure connections','24 posts and one guide','Data-center connectivity opportunities','Technical stakeholder engagement','Do not expose private network architecture or facility security information',CURRENT_TIMESTAMP),
('Telecom Procurement Advisor','Advisor','CFOs, sourcing leaders and IT procurement','IT and legal teams','RFQs, bid structures, requirements, negotiation and vendor comparison','Telecom sourcing becomes inconsistent when requirements, quotes and contractual terms are not normalized','Helping procurement and IT teams compare telecom offers on more than monthly price','The Telecom Buyer’s Table',2,2,20,25,'Telecom RFQ Template','Negotiation experience, anonymized sourcing events and contract comparisons','Document posts, tables and negotiation lessons','Apples-to-apples quote comparison; term leverage; construction charges; renewal timing','Telecom RFQ and Bid Comparison Template','I can send our bid-comparison structure.','Upcoming RFP, renewal, sourcing initiative or concern about current rates','Route with spend range, service inventory and decision timeline','Carrier Analyst, Contract Advisor and Finance Advisor','800 procurement and finance connections','30 posts and one template','Sourcing projects','Template requests and CFO engagement','Do not disclose protected pricing or represent general advice as legal advice',CURRENT_TIMESTAMP),
('Telecom Contract and Renewal Advisor','Advisor','CFOs, legal teams, procurement and IT executives','Technology advisors and contract managers','Telecom agreements, renewal calendars, notice periods, ETFs and commercial risk','Organizations miss notice windows, accept automatic renewals and fail to connect service changes to contract obligations','Helping organizations understand the operational and financial consequences hidden in telecom agreements','Before You Sign the Renewal',2,1,15,20,'Telecom Contract Review Checklist','Contract experience, common commercial structures and anonymized disputes','Text explainers and deadline checklists','Auto-renewal; termination liability; service-level credits; assignment clauses; renewal calendars','Telecom Contract Review Checklist','I can share the operational checklist we use before legal review.','Renewal notice approaching, merger, relocation, disconnect issue or ETF dispute','Route to procurement owner and recommend legal counsel where appropriate','Procurement Advisor, Finance Advisor and Customer Success Advisor','500 legal, procurement and IT connections','24 posts and one checklist','Contract-review conversations','Checklist downloads','Explicitly state that content is operational perspective, not legal advice',CURRENT_TIMESTAMP),
('Telecom Finance and Cost Optimization Advisor','Advisor','CFOs, controllers and finance leaders','Procurement and IT leaders','Spend visibility, billing, cost allocation, audit and financial comparison','Finance teams struggle to reconcile telecom invoices, commitments, credits and location-level ownership','Helping finance and IT turn telecom spend into something understandable and controllable','Where the Telecom Money Goes',2,1,15,20,'Telecom Spend Baseline Worksheet','Billing analyses, cost models, public financial concepts and anonymized examples','Tables, before-and-after examples and worksheets','Unused services; invoice variance; effective rate; total cost beyond MRC','Telecom Spend Baseline Worksheet','I can send the baseline model.','Expense reduction program, billing dispute, acquisition or inability to inventory spend','Route with invoice count, approximate spend and scope','Procurement Advisor, Contract Advisor and Data Analyst','500 finance and procurement connections','24 posts and one worksheet','Cost-optimization assessments','Worksheet requests','Do not guarantee savings or publish private financial data',CURRENT_TIMESTAMP),
('Implementation and Project Management Advisor','Advisor','IT program managers, store development and infrastructure leaders','Construction teams, carriers and vendors','Telecom provisioning, milestones, dependencies, escalations and multi-site rollout governance','Orders fail because responsibilities, dependencies, construction and acceptance steps are not actively managed','Helping organizations turn signed telecom orders into working services without losing control of the timeline','From Order to Turn-Up',2,2,20,20,'Circuit Implementation Milestone Template','Provisioning experience, delays, escalation lessons and project retrospectives','Timelines, postmortems and practical checklists','FOC dates; site readiness; demarc extensions; testing; construction; acceptance','Circuit Implementation Milestone Tracker','I can share the milestone tracker.','Buyer mentions delayed installs, openings, migrations or lack of carrier status','Route to implementation sales owner with affected orders and critical dates','Retail Advisor, Construction Advisor and Customer Success Advisor','600 program-management and IT connections','30 posts and one tracker','Implementation-managed opportunities','Tracker downloads','Never expose live customer order details or blame named individuals',CURRENT_TIMESTAMP)
ON CONFLICT(role_name) DO UPDATE SET
 relationship_type=excluded.relationship_type,primary_audience=excluded.primary_audience,secondary_audience=excluded.secondary_audience,
 primary_expertise=excluded.primary_expertise,core_buyer_problem=excluded.core_buyer_problem,positioning_statement=excluded.positioning_statement,
 recurring_series=excluded.recurring_series,weekly_original_posts=excluded.weekly_original_posts,weekly_short_posts=excluded.weekly_short_posts,
 weekly_meaningful_comments=excluded.weekly_meaningful_comments,weekly_new_connections=excluded.weekly_new_connections,
 monthly_long_form_asset=excluded.monthly_long_form_asset,content_sources=excluded.content_sources,primary_post_formats=excluded.primary_post_formats,
 example_topics=excluded.example_topics,lead_magnet=excluded.lead_magnet,soft_cta=excluded.soft_cta,
 qualified_buying_signal=excluded.qualified_buying_signal,lead_handoff_action=excluded.lead_handoff_action,
 cross_team_collaboration=excluded.cross_team_collaboration,ninety_day_audience_goal=excluded.ninety_day_audience_goal,
 ninety_day_content_goal=excluded.ninety_day_content_goal,primary_kpi=excluded.primary_kpi,secondary_kpi=excluded.secondary_kpi,
 guardrail=excluded.guardrail,updated_at=CURRENT_TIMESTAMP;

INSERT INTO playbooks (
 role_name,relationship_type,primary_audience,secondary_audience,primary_expertise,core_buyer_problem,positioning_statement,recurring_series,
 weekly_original_posts,weekly_short_posts,weekly_meaningful_comments,weekly_new_connections,monthly_long_form_asset,content_sources,primary_post_formats,
 example_topics,lead_magnet,soft_cta,qualified_buying_signal,lead_handoff_action,cross_team_collaboration,ninety_day_audience_goal,ninety_day_content_goal,
 primary_kpi,secondary_kpi,guardrail,updated_at
) VALUES
('Field Services and Inside Wiring Advisor','Advisor','IT directors, facilities, construction and project managers','Low-voltage contractors and property managers','Demarc extensions, inside wiring, smart hands, site surveys and on-site coordination','Carrier service can be delivered to the building but still fail to reach the customer equipment','Helping teams close the gap between carrier handoff and usable service at the rack','The Last 100 Feet',2,1,15,20,'Site Readiness Checklist','Site surveys, wiring problems, demarcation issues and installation photos with permission','Annotated diagrams, photo lessons and checklists','MPOE versus demarc; fiber connectors; patching; power; rack readiness','Site Readiness Checklist','I can send the site-readiness sheet.','New office, circuit turn-up, construction, remote troubleshooting or failed activation','Route with address, handoff type, photos through secure channel and due date','Project Manager, Network Engineer and Construction Advisor','400 facilities and IT connections','24 posts and one checklist','Field-service opportunities','Site-checklist requests','Do not publish access instructions, security-sensitive photos or customer locations without approval',CURRENT_TIMESTAMP),
('Customer Success and Escalations Advisor','Advisor','CIOs, IT directors and operations leaders','Carrier service managers and technology advisors','Service ownership, escalation, outage communications and customer lifecycle','Customers often feel abandoned after the order is signed and lack organized escalation paths','Helping organizations manage telecom after the sale, when service quality and accountability actually matter','What Happens After Installation',2,1,20,20,'Telecom Escalation Readiness Guide','Support experience, anonymized incidents and communication practices','Incident lessons, communication templates and customer stories','Escalation packets; ticket ownership; outage communication; SLA documentation','Telecom Escalation Readiness Guide','I can send the escalation checklist.','Repeated outages, unresolved tickets, billing errors or poor incumbent support','Route immediately when active incident exists; otherwise schedule service review','Carrier Relationship Advisor, Project Manager and Network Engineer','600 IT operations connections','24 posts and one guide','Service-management opportunities','Response quality and direct messages','Do not publicly litigate active disputes or reveal ticket data',CURRENT_TIMESTAMP),
('Network Uptime and Outage Analyst','Contractor','IT operations, NOC leaders and infrastructure executives','Technology advisors and carrier operations teams','Outage analysis, resilience lessons, monitoring and incident patterns','Buyers receive outage notifications without understanding architectural impact or prevention options','Helping IT leaders turn outages into better resilience decisions','Outage Lesson of the Week',2,2,25,20,'Quarterly Resilience Lessons Report','Public outage information, monitoring data approved for publication and anonymized incidents','Incident timelines, diagrams and concise reports','What an outage reveals about backup design; DNS versus access failure; monitoring blind spots','Network Resilience Review Checklist','I can share the resilience review structure.','Buyer reports downtime, failover failure or insufficient monitoring','Route to network and customer-success owners','Network Engineer, Wireless Advisor and Customer Success Advisor','700 NOC and infrastructure connections','30 posts and one report','Resilience assessments','High-quality IT operations engagement','Verify facts before publishing; clearly distinguish confirmed facts from hypotheses',CURRENT_TIMESTAMP),
('Telecom Data and Research Analyst','Contractor','CIOs, procurement and technology advisors','Industry analysts and carrier leaders','Industry research, location data, provider availability and trend analysis','Market conversations often rely on anecdotes rather than structured evidence','Helping telecom buyers separate useful evidence from industry folklore','The Telecom Data Point',2,2,20,20,'Quarterly Telecom Market Brief','Public datasets, approved internal aggregates, provider announcements and regulatory sources','Charts, maps, tables and research summaries','Provider availability by market; expansion announcements; pricing variables; technology adoption','Telecom Market Brief','I can send the underlying methodology and brief.','Buyer requests market benchmark, location analysis or expansion intelligence','Route to analyst-supported discovery session','Carrier Analyst, Founder and Procurement Advisor','700 analytical and telecom connections','30 posts and one quarterly brief','Research-driven opportunities','Shares and citations by industry professionals','Cite sources, date datasets and avoid presenting incomplete data as comprehensive',CURRENT_TIMESTAMP),
('Telecom Compliance and Risk Advisor','Advisor','Government contractors, regulated-industry IT and security leaders','Procurement and legal stakeholders','Telecom vendor risk, documentation, continuity requirements and compliance-aware sourcing','Regulated buyers need commercial connectivity decisions to align with security and contractual obligations','Helping regulated organizations ask better risk and documentation questions during telecom sourcing','Connectivity Risk Questions',2,1,15,15,'Connectivity Vendor Risk Questionnaire','Official requirements, public guidance and professional experience','Text explainers, questionnaires and risk scenarios','Vendor documentation; subcontractor visibility; continuity; service dependencies','Connectivity Vendor Risk Questionnaire','I can share the questions we use to start the review.','Compliance initiative, customer requirement, government contract or vendor-risk review','Route to compliance-aware sales owner and appropriate counsel or security stakeholders','Government Advisor, Security Advisor and Procurement Advisor','400 regulated-industry connections','24 posts and one questionnaire','Risk-assessment conversations','Questionnaire requests','Do not provide legal conclusions, certifications or assurances beyond verified facts',CURRENT_TIMESTAMP),
('Telecom Careers and Workforce Advisor','Contractor','Telecom professionals, carrier employees and hiring managers','University programs and military-transition communities','Telecom careers, transferable skills, industry knowledge and workforce development','The industry needs experienced professionals, but much of its practical knowledge remains undocumented','Helping experienced telecom professionals share what they know and helping new people understand the industry','How Telecom Actually Works',2,2,20,25,'Telecom Career Map','Career interviews, role explanations and contributor stories','Interviews, career posts and practical explainers','Carrier operations roles; broker careers; project management; veterans in telecom','Telecom Career Map','I can send the role map or introduce you to the series.','Candidate, expert or potential advisor expresses interest in contributing','Route talent opportunities to leadership; commercial signals to sales','All 25 contributors','1,000 telecom-industry connections','30 posts and six interviews','Contributor recruitment and audience growth','Employee and carrier engagement','Do not imply employment offers or disclose confidential compensation',CURRENT_TIMESTAMP),
('Local Business and Community Connectivity Advisor','Advisor','Local CEOs, chamber members, business owners and nonprofit leaders','Local MSPs, commercial brokers and economic-development organizations','SMB connectivity, local service options, relocations and practical technology buying','Local businesses often buy connectivity without expert comparison or implementation support','Helping local organizations make practical Internet and communications decisions without navigating carriers alone','Connected Pensacola Business',2,1,20,25,'Local Business Connectivity Checklist','Local events, economic development, business openings and common local issues','Local stories, event posts and practical guides','New offices; storm resilience; backup Internet; local carrier availability','Local Connectivity Planning Checklist','I’m happy to share the checklist with any local business planning a move.','Business move, expansion, storm-readiness concern or unreliable service','Route to local sales owner with business details and timeline','Commercial Real Estate Advisor, Wireless Advisor and MSP Advisor','800 regional business connections','24 posts and one local guide','Local appointments','Local introductions and event invitations','Avoid exploiting disasters or making unsupported local availability claims',CURRENT_TIMESTAMP),
('Editorial Director / Telecom Newsroom Lead','Contractor','Internal contributor team','Managed Circuits leadership and sales','Content strategy, quality control, editorial planning and campaign orchestration','Without coordination, 25 experts will repeat topics, lose consistency or stop publishing','Turning 25 real careers into a coordinated telecom knowledge network without erasing individual voices','Managed Circuits Weekly Intelligence Desk',1,2,20,15,'Weekly Editorial Intelligence Packet','Contributor interviews, approved company developments, public news, sales insights and editorial calendar','Editorial notes, roundup posts and contributor spotlights','Weekly themes; unanswered buyer questions; contributor stories; campaign retrospectives','Weekly Telecom Intelligence Brief','Subscribe or follow the contributors covering your area.','Audience requests a specialist introduction or asks a cross-functional question','Route to the correct specialist and record content attribution','Coordinates all roles while preventing identical posts','600 industry and media connections','12 intelligence packets and 15 editorial posts','On-time contributor publishing','Percentage of posts requiring revision','No ghostwritten claim may exceed the contributor’s real knowledge or experience',CURRENT_TIMESTAMP),
('Video Host and Interviewer','Contractor','CIOs, telecom professionals and business leaders','All vertical audiences','Expert interviewing, short-form video and customer-safe storytelling','Experienced telecom professionals possess valuable knowledge but may not naturally turn it into accessible content','Extracting practical telecom lessons from the people who have actually done the work','Three Questions With a Telecom Veteran',2,3,20,20,'Monthly Expert Interview Compilation','Interviews with contributors, partners and approved customers','Short videos, interview clips and quote cards','Retail opening lessons; worst provisioning surprises; advice to first-time telecom buyers','Expert Interview Library','Which specialist should I interview next?','Viewer requests introduction, resource or advice tied to an interview','Route to featured expert and sales owner when commercial need exists','Interviews every specialist over the quarter','800 telecom and IT connections','36 videos and 12 interviews','Qualified conversations from video','Video completion and direct responses','Obtain permission, avoid scripted testimonials and label relationships accurately',CURRENT_TIMESTAMP),
('Managed Circuits Company Page','Organization Page','All target buyers, partners and contributors','Industry media and recruits','Company proof, coordinated resources, case studies and contributor discovery','Prospects need a trusted home where they can verify the company and explore its expertise','Managed Circuits helps organizations source, implement and manage business connectivity across providers and locations','Meet the Managed Circuits Experts',3,2,30,0,'Monthly Telecom Procurement Brief','Approved company information, contributor posts, customer-approved stories and public research','Documents, videos, case studies and team spotlights','Contributor features; service explainers; anonymized outcomes; market briefs','Managed Circuits Resource Library','Follow the advisor who covers your industry.','Page visitor requests assessment, introduction or resource','Route by vertical and originating page content','Features 4-6 contributors monthly without reposting every personal post','2,000 relevant followers','40 posts, three documents and six videos','Page-sourced opportunities','Target-account follower growth','Page should support authentic personal voices, not manufacture employee activity',CURRENT_TIMESTAMP)
ON CONFLICT(role_name) DO UPDATE SET
 relationship_type=excluded.relationship_type,primary_audience=excluded.primary_audience,secondary_audience=excluded.secondary_audience,
 primary_expertise=excluded.primary_expertise,core_buyer_problem=excluded.core_buyer_problem,positioning_statement=excluded.positioning_statement,
 recurring_series=excluded.recurring_series,weekly_original_posts=excluded.weekly_original_posts,weekly_short_posts=excluded.weekly_short_posts,
 weekly_meaningful_comments=excluded.weekly_meaningful_comments,weekly_new_connections=excluded.weekly_new_connections,
 monthly_long_form_asset=excluded.monthly_long_form_asset,content_sources=excluded.content_sources,primary_post_formats=excluded.primary_post_formats,
 example_topics=excluded.example_topics,lead_magnet=excluded.lead_magnet,soft_cta=excluded.soft_cta,
 qualified_buying_signal=excluded.qualified_buying_signal,lead_handoff_action=excluded.lead_handoff_action,
 cross_team_collaboration=excluded.cross_team_collaboration,ninety_day_audience_goal=excluded.ninety_day_audience_goal,
 ninety_day_content_goal=excluded.ninety_day_content_goal,primary_kpi=excluded.primary_kpi,secondary_kpi=excluded.secondary_kpi,
 guardrail=excluded.guardrail,updated_at=CURRENT_TIMESTAMP;
