import type { AgentDefinition } from "./types";

export const BUILTIN_AGENT_DEFINITIONS: AgentDefinition[] = [
  { slug:"strategy-agent", name:"Strategy Agent", category:"Content & LinkedIn", role:"Content strategy", purpose:"Builds employee positioning and strategy briefs for gated orchestration.", owner:"Marketing", status:"active", autonomy:"Human-gated", provider:"OpenAI", model:"Existing configured model", capabilities:["READ","ANALYZE","DRAFT"], tools:["Employees","Playbooks","Strategy briefs"], route:"/orchestration", implementation:"existing" },
  { slug:"content-planner", name:"Content Planner", category:"Content & LinkedIn", role:"Weekly planning", purpose:"Builds validated weekly plans and prevents duplicate topics.", owner:"Marketing", status:"active", autonomy:"Human-gated", provider:"OpenAI", model:"Existing configured model", capabilities:["READ","ANALYZE","DRAFT"], tools:["Playbooks","Content plans","Post metrics"], route:"/planner", implementation:"existing" },
  { slug:"post-drafting-agent", name:"Post Drafting Agent", category:"Content & LinkedIn", role:"Employee-aware writer", purpose:"Drafts posts in each employee's approved voice without publishing them.", owner:"Marketing", status:"active", autonomy:"Draft only", provider:"OpenAI", model:"Existing configured model", capabilities:["READ","DRAFT","APPROVAL_REQUIRED"], tools:["Employees","Playbooks","Content drafts"], route:"/#content", implementation:"existing" },
  { slug:"image-generation", name:"Image Generation", category:"Content & LinkedIn", role:"Content image tool", purpose:"Generates images for existing drafts; image review remains human-controlled.", owner:"Marketing", status:"active", autonomy:"Draft only", provider:"OpenAI", model:"Existing image model", capabilities:["READ","DRAFT","APPROVAL_REQUIRED"], tools:["Content drafts","R2 image storage"], route:"/#content", implementation:"existing" },
  { slug:"connection-targeting-agent", name:"Connection Targeting Agent", category:"Marketing", role:"Network recommendations", purpose:"Scores prospects and drafts connection recommendations.", owner:"Marketing", status:"active", autonomy:"Human-gated", provider:"OpenAI", model:"Existing configured model", capabilities:["READ","ANALYZE","DRAFT"], tools:["Prospects","Employees","Playbooks","Buying signals"], route:"/connections", implementation:"existing" },
  { slug:"engagement-queue-agent", name:"Engagement Queue Agent", category:"Marketing", role:"Engagement triage", purpose:"Surfaces existing activity and conversations worth human engagement.", owner:"Marketing", status:"active", autonomy:"Read/analyze", provider:"Rules + existing data", model:"No separate model", capabilities:["READ","ANALYZE"], tools:["Activity","Conversations","Recommendations"], route:"/connections", implementation:"existing" },
  { slug:"conversation-signal-agent", name:"Conversation Signal Agent", category:"Marketing", role:"Signal analysis", purpose:"Uses recorded conversations and buying signals to identify lead potential.", owner:"Sales", status:"active", autonomy:"Read/analyze", provider:"Rules + existing data", model:"No separate model", capabilities:["READ","ANALYZE"], tools:["Conversations","Buying signals","Lead handoffs"], route:"/connections", implementation:"existing" },
  { slug:"messaging-agent", name:"Messaging Agent", category:"Existing Automation", role:"Reply drafting concept", purpose:"Drafting concept only; it cannot send public replies or private messages.", owner:"Marketing", status:"waiting", autonomy:"Not connected", provider:"Not activated", model:"None", capabilities:["READ","DRAFT","APPROVAL_REQUIRED"], tools:["No sending tool"], implementation:"scaffold" },
  { slug:"lead-routing-agent", name:"Lead Routing Agent", category:"Existing Automation", role:"Handoff routing", purpose:"Represents existing lead-handoff records without changing their workflow.", owner:"Sales", status:"active", autonomy:"Human-gated", provider:"Existing workflow", model:"None", capabilities:["READ","ANALYZE"], tools:["Lead handoffs","Employees"], route:"/#activity", implementation:"existing" },
  { slug:"post-orchestration", name:"Post Orchestration", category:"Existing Automation", role:"Gated workflow", purpose:"Runs strategy, planning, and drafting stages with explicit approval handoffs.", owner:"Marketing", status:"active", autonomy:"Human-gated", provider:"OpenAI", model:"Stage-recorded model", capabilities:["READ","ANALYZE","DRAFT","APPROVAL_REQUIRED"], tools:["Orchestration runs","Stages","Handoffs","Content drafts"], route:"/orchestration", implementation:"existing" },
  { slug:"daily-autopilot", name:"Daily Operations Autopilot", category:"Existing Automation", role:"Scheduled content preparation", purpose:"Queues daily post generation and high-score connection approvals under existing settings.", owner:"Operations", status:"active", autonomy:"Existing configured gates", provider:"OpenAI + rules", model:"Existing configured model", capabilities:["READ","ANALYZE","DRAFT","APPROVAL_REQUIRED"], tools:["Automation runs","Tasks","Content drafts","Recommendations"], route:"/operations", implementation:"existing" },
  { slug:"issue-hunter", name:"Issue Hunter", category:"Development", role:"Work discovery", purpose:"Analyzes Development records and drafts candidate Development Requests.", owner:"Development", status:"active", autonomy:"Read/analyze/draft", provider:"Deterministic control plane", model:"No model call", capabilities:["READ","ANALYZE","DRAFT"], tools:["Development Requests","Activity"], implementation:"new" },
  { slug:"release-readiness", name:"Release Readiness", category:"Development", role:"Release analysis", purpose:"Summarizes QA and promotion readiness without changing human QA state.", owner:"Development", status:"active", autonomy:"Read/analyze", provider:"Deterministic control plane", model:"No model call", capabilities:["READ","ANALYZE"], tools:["Development Requests","QA state","Branch state"], implementation:"new" },
  { slug:"qa-agent", name:"QA Agent", category:"Development", role:"QA handoff assistant", purpose:"Drafts QA handoff guidance from recorded data and never invents URLs.", owner:"Development", status:"active", autonomy:"Draft only", provider:"Deterministic control plane", model:"No model call", capabilities:["READ","ANALYZE","DRAFT"], tools:["Development Requests","QA handoffs"], implementation:"new" },
  { slug:"pr-reviewer", name:"PR Reviewer", category:"Development", role:"Pull request review", purpose:"Will analyze pull requests after the read-only GitHub connection is installed.", owner:"Development", status:"waiting", autonomy:"Not connected", provider:"Not activated", model:"None", capabilities:["READ","ANALYZE"], tools:["GitHub read adapter"], implementation:"scaffold" },
  { slug:"chief-of-staff", name:"Chief of Staff", category:"Cross-functional", role:"Operating brief", purpose:"Summarizes Development, content, approvals, agent activity, and priority work.", owner:"Adam", status:"active", autonomy:"Read/analyze", provider:"Deterministic control plane", model:"No model call", capabilities:["READ","ANALYZE"], tools:["Development","Content","Approvals","Agent runs"], implementation:"new" },
];

export function getAgentDefinition(slug: string) { return BUILTIN_AGENT_DEFINITIONS.find((agent) => agent.slug === slug) || null; }
